CREATE  TABLE users (
  username VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT 1,
  PRIMARY KEY (username)
);

CREATE TABLE user_roles (
  user_role_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(45) NOT NULL,
  role varchar(45) NOT NULL,
  PRIMARY KEY (user_role_id),
  CONSTRAINT uniq_username_role UNIQUE (role,username),
  FOREIGN KEY (username) REFERENCES users(username)
);